env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'eslint-config-prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 2
    - { 'SwitchCase': 1 }
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars:
    - error
    - { argsIgnorePattern: '^_' } # 変数名がアンダーバーで始まる場合のみ許可
